// <auto-generated />
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240605170934_AddDefaultValues")]
    partial class AddDefaultValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Domain.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eletrônicos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Roupas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Livros"
                        });
                });

            modelBuilder.Entity("Domain.Models.Entities.CategoryProduct", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 10
                        });
                });

            modelBuilder.Entity("Domain.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Smartphone",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Laptop",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Camiseta",
                            Price = 10m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Calça Jeans",
                            Price = 100m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Livro de Romance",
                            Price = 30m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Livro de Drama",
                            Price = 200m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Fones de ouvido",
                            Price = 300m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Smartwatch",
                            Price = 800m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Jaqueta",
                            Price = 150m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non malesuada nunc. Sed ultricies interdum bibendum. Suspendisse placerat ipsum eu ullamcorper accumsan. Nulla sollicitudin faucibus ipsum, et dictum felis. Quisque tincidunt eros efficitur tellus congue molestie. Phasellus eu rutrum ante. Integer condimentum, elit et euismod porta, quam lectus venenatis urna, nec suscipit nisi nisl eget dui. Curabitur vehicula auctor eros, nec imperdiet odio tristique id. In sollicitudin sollicitudin augue, vitae tempor risus eleifend ut. Suspendisse tincidunt congue justo, et accumsan tortor suscipit vel. Sed sit amet gravida quam. Donec maximus nec nulla a gravida. Morbi ut lectus venenatis, hendrerit odio eu, varius ante. Vivamus feugiat sollicitudin turpis, ut auctor nisl molestie quis.",
                            Name = "Livro de Biografia",
                            Price = 40m
                        });
                });

            modelBuilder.Entity("Domain.Models.Entities.CategoryProduct", b =>
                {
                    b.HasOne("Domain.Models.Entities.Category", "Category")
                        .WithMany("CategoriesProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Entities.Product", "Product")
                        .WithMany("CategoriesProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Models.Entities.Category", b =>
                {
                    b.Navigation("CategoriesProducts");
                });

            modelBuilder.Entity("Domain.Models.Entities.Product", b =>
                {
                    b.Navigation("CategoriesProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
